-- =====================================================================
-- 0001_schema.sql  —  glow_saha / Neşe Yönetim: MySQL -> PostgreSQL portu
-- Tam Supabase-native geçiş. Şema, MySQL db/schema.sql ile birebir eşdeğerdir.
--
-- Not: id sütunları "generated by default as identity" — veri göçünde
-- mevcut id'ler açıkça verilebilsin diye (always değil).
-- =====================================================================

-- ---------------------------------------------------------------------
-- JWT claim yardımcıları (özel auth korunuyor; login Edge Function
-- firma_id / personel_id / rol claim'lerini token'a gömer, RLS bunları okur).
-- ---------------------------------------------------------------------
create schema if not exists app;

create or replace function app.current_firma_id() returns bigint
    language sql stable
    as $$ select nullif(auth.jwt() ->> 'firma_id', '')::bigint $$;

create or replace function app.current_personel_id() returns bigint
    language sql stable
    as $$ select nullif(auth.jwt() ->> 'personel_id', '')::bigint $$;

create or replace function app.current_rol() returns text
    language sql stable
    as $$ select auth.jwt() ->> 'rol' $$;

create or replace function app.is_yonetici() returns boolean
    language sql stable
    as $$ select coalesce(auth.jwt() ->> 'rol', '') = 'yonetici' $$;

-- ---------------------------------------------------------------------
-- Enum tipleri (MySQL ENUM karşılığı)
-- ---------------------------------------------------------------------
create type personel_rol   as enum ('yonetici', 'temizlik', 'teknik');
create type is_emri_durum   as enum ('bekliyor', 'devam_ediyor', 'tamamlandi', 'iptal');
create type ariza_durum     as enum ('acik', 'bekliyor', 'cozuldu', 'iptal', 'dis_destek');
create type ariza_oncelik   as enum ('dusuk', 'normal', 'yuksek');
create type masraf_durum    as enum ('bekliyor', 'onaylandi', 'reddedildi');
create type tekrar_tipi     as enum ('gunluk', 'haftalik', 'aylik');

-- ---------------------------------------------------------------------
-- 1. FİRMALAR
-- ---------------------------------------------------------------------
create table firmalar (
    id                bigint generated by default as identity primary key,
    firma_kodu        varchar(50) not null unique,
    ad                varchar(255) not null,
    logo              varchar(255),
    hex_color         varchar(10) default '#000000',
    olusturma_tarihi  timestamptz not null default now(),
    aktif             boolean not null default true
);

-- ---------------------------------------------------------------------
-- 2. PERSONELLER  (Multi-Tenant: firma_id)
-- ---------------------------------------------------------------------
create table personeller (
    id                bigint generated by default as identity primary key,
    firma_id          bigint not null references firmalar(id) on delete cascade,
    ad_soyad          varchar(255) not null,
    telefon           varchar(20) not null,
    sifre             varchar(255) not null,       -- bcrypt/argon hash
    rol               personel_rol not null,
    fcm_token         varchar(255),
    olusturma_tarihi  timestamptz not null default now(),
    aktif             boolean not null default true,
    unique (firma_id, telefon)                     -- bir firmada telefon benzersiz
);

-- ---------------------------------------------------------------------
-- 3. SİTELER / TESİSLER  (Multi-Tenant: firma_id)
-- ---------------------------------------------------------------------
create table siteler (
    id                bigint generated by default as identity primary key,
    firma_id          bigint not null references firmalar(id) on delete cascade,
    ad                varchar(255) not null,
    adres             text,
    enlem             numeric(10, 8),
    boylam            numeric(11, 8),
    qr_kod            varchar(100) unique,         -- tesise asılan benzersiz QR
    olusturma_tarihi  timestamptz not null default now(),
    aktif             boolean not null default true
);

-- ---------------------------------------------------------------------
-- 8. PERİYODİK GÖREV ŞABLONLARI  (is_emirleri FK'sinden önce oluşturulmalı)
-- ---------------------------------------------------------------------
create table periyodik_sablonlar (
    id                bigint generated by default as identity primary key,
    firma_id          bigint not null references firmalar(id) on delete cascade,
    site_id           bigint not null references siteler(id) on delete cascade,
    personel_id       bigint not null references personeller(id) on delete cascade,
    baslik            varchar(255) not null,
    aciklama          text,
    alt_gorevler      text,                        -- checklist maddeleri (satır satır)
    tekrar_tipi       tekrar_tipi not null default 'gunluk',
    tekrar_gunu       smallint,                    -- haftalik:1-7 | aylik:1-31 | gunluk:NULL
    son_uretim_tarihi date,                        -- aynı gün mükerrer üretimi engeller
    aktif             boolean not null default true,
    olusturma_tarihi  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 4. İŞ EMİRLERİ  (Multi-Tenant: firma_id)
-- ---------------------------------------------------------------------
create table is_emirleri (
    id                          bigint generated by default as identity primary key,
    firma_id                    bigint not null references firmalar(id) on delete cascade,
    site_id                     bigint not null references siteler(id) on delete cascade,
    personel_id                 bigint not null references personeller(id) on delete cascade,
    sablon_id                   bigint references periyodik_sablonlar(id) on delete set null,
    baslik                      varchar(255) not null,
    aciklama                    text,
    durum                       is_emri_durum not null default 'bekliyor',
    qr_kod                      varchar(100),
    planlanan_baslangic_tarihi  timestamptz,
    termin_tarihi               date,              -- SLA: en geç bitiş
    tamamlanma_tarihi           timestamptz,
    tamamlanma_enlem            numeric(10, 8),
    tamamlanma_boylam           numeric(11, 8),
    kapanis_fotograf_url        varchar(255),
    olusturma_tarihi            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 5. İŞ EMİRLERİ ALT GÖREVLER (CHECKLIST)
-- ---------------------------------------------------------------------
create table is_emirleri_alt_gorevler (
    id           bigint generated by default as identity primary key,
    firma_id     bigint not null references firmalar(id) on delete cascade,
    is_emri_id   bigint not null references is_emirleri(id) on delete cascade,
    gorev_metni  varchar(255) not null,
    yapildi_mi   boolean not null default false
);

-- ---------------------------------------------------------------------
-- 6. ARIZALAR  (Multi-Tenant: firma_id)
-- ---------------------------------------------------------------------
create table arizalar (
    id                    bigint generated by default as identity primary key,
    firma_id              bigint not null references firmalar(id) on delete cascade,
    site_id               bigint not null references siteler(id) on delete cascade,
    bildiren_personel_id  bigint not null references personeller(id) on delete cascade,
    teknik_personel_id    bigint references personeller(id) on delete set null,
    baslik                varchar(255) not null,
    aciklama              text,
    teknik_notu           text,
    fotograf_url          varchar(255),
    cozum_fotograf_url    varchar(255),
    durum                 ariza_durum not null default 'acik',
    oncelik               ariza_oncelik not null default 'normal',
    olusturma_tarihi      timestamptz not null default now(),
    cozum_tarihi          timestamptz
);

-- ---------------------------------------------------------------------
-- 7. MALZEME / MASRAF TALEPLERİ  (Multi-Tenant: firma_id)
-- ---------------------------------------------------------------------
create table malzeme_talepleri (
    id                   bigint generated by default as identity primary key,
    firma_id             bigint not null references firmalar(id) on delete cascade,
    personel_id          bigint not null references personeller(id) on delete cascade,
    ariza_id             bigint references arizalar(id) on delete cascade,
    is_emri_id           bigint references is_emirleri(id) on delete cascade,
    kalem_adi            varchar(255) not null,
    tutar                numeric(10, 2) not null,
    fis_fatura_fotograf  varchar(255) not null,
    durum                masraf_durum not null default 'bekliyor',
    olusturma_tarihi     timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 9. DENETİM İZİ (AUDIT LOG)
-- ---------------------------------------------------------------------
create table audit_log (
    id                bigint generated by default as identity primary key,
    firma_id          bigint not null references firmalar(id) on delete cascade,
    personel_id       bigint references personeller(id) on delete set null,
    eylem             varchar(60) not null,   -- ör: masraf_onay, personel_sil
    hedef_tip         varchar(40),            -- ör: masraf, personel, ariza
    hedef_id          bigint,
    detay             text,                   -- serbest açıklama / JSON
    ip                varchar(45),
    olusturma_tarihi  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 10. PERFORMANS İNDEKSLERİ  (multi-tenant: firma_id + durum/tarih)
-- ---------------------------------------------------------------------
create index idx_personel_firma            on personeller (firma_id);
create index idx_site_firma                on siteler (firma_id);
create index idx_ie_firma_durum            on is_emirleri (firma_id, durum);
create index idx_ie_firma_personel_durum   on is_emirleri (firma_id, personel_id, durum);
create index idx_ie_firma_tamamlanma       on is_emirleri (firma_id, tamamlanma_tarihi);
create index idx_ie_sablon                 on is_emirleri (sablon_id);
create index idx_altgorev_isemri           on is_emirleri_alt_gorevler (is_emri_id);
create index idx_ar_firma_durum            on arizalar (firma_id, durum);
create index idx_mt_firma_durum            on malzeme_talepleri (firma_id, durum);
create index idx_mt_firma_tarih            on malzeme_talepleri (firma_id, olusturma_tarihi);
create index idx_sablon_firma              on periyodik_sablonlar (firma_id);
create index idx_al_firma_tarih            on audit_log (firma_id, olusturma_tarihi);
create index idx_al_firma_eylem            on audit_log (firma_id, eylem);
